spring.application.name=food-backend

server.port=8080

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mariadb://localhost:3306/example}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:fooduser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:foodpass}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
